-- Create users table
CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role ENUM('super_admin', 'admin', 'user_brand') DEFAULT 'user_brand',
  id_brand INT UNSIGNED DEFAULT NULL,
  avatar VARCHAR(500) DEFAULT NULL,
  phone VARCHAR(20) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_email (email),
  FOREIGN KEY (id_brand) REFERENCES brand(id)
);

CREATE TABLE IF NOT EXISTS brand (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nama_brand VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS data_shopee (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  id_brand INT UNSIGNED NOT NULL,
  dari_tanggal DATE NOT NULL,
  sampai_tanggal DATE NOT NULL,
  shopee_penghasilan_saya VARCHAR(255) NOT NULL,
  shopee_pesanan_saya VARCHAR(255) NOT NULL,
  shopee_biaya_iklan VARCHAR(255) NOT NULL,
  variasi_1 VARCHAR(255) DEFAULT NULL,
  variasi_2 VARCHAR(255) DEFAULT NULL,
  orders_reference_column VARCHAR(255) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (id_brand) REFERENCES brand(id)
);

CREATE TABLE IF NOT EXISTS hpp_produk (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  id_brand INT UNSIGNED NOT NULL,
  nama_produk VARCHAR(255) NOT NULL,
  hpp VARCHAR(255) NOT NULL,
  variasi_1 VARCHAR(255) DEFAULT NULL,
  variasi_2 VARCHAR(255) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (id_brand) REFERENCES brand(id)
);
