/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AdminHppProdukRouteImport } from './routes/admin/hpp-produk'
import { Route as AdminBrandRouteImport } from './routes/admin/brand'
import { Route as AdminDataShopeeIndexRouteImport } from './routes/admin/data-shopee/index'
import { Route as AdminDataShopeeIdRouteImport } from './routes/admin/data-shopee/$id'

const RegisterLazyRouteImport = createFileRoute('/register')()
const LoginLazyRouteImport = createFileRoute('/login')()
const IndexLazyRouteImport = createFileRoute('/')()

const RegisterLazyRoute = RegisterLazyRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/register.lazy').then((d) => d.Route))
const LoginLazyRoute = LoginLazyRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const AdminHppProdukRoute = AdminHppProdukRouteImport.update({
  id: '/hpp-produk',
  path: '/hpp-produk',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBrandRoute = AdminBrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDataShopeeIndexRoute = AdminDataShopeeIndexRouteImport.update({
  id: '/data-shopee/',
  path: '/data-shopee/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDataShopeeIdRoute = AdminDataShopeeIdRouteImport.update({
  id: '/data-shopee/$id',
  path: '/data-shopee/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginLazyRoute
  '/register': typeof RegisterLazyRoute
  '/admin/brand': typeof AdminBrandRoute
  '/admin/hpp-produk': typeof AdminHppProdukRoute
  '/admin/data-shopee/$id': typeof AdminDataShopeeIdRoute
  '/admin/data-shopee/': typeof AdminDataShopeeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginLazyRoute
  '/register': typeof RegisterLazyRoute
  '/admin/brand': typeof AdminBrandRoute
  '/admin/hpp-produk': typeof AdminHppProdukRoute
  '/admin/data-shopee/$id': typeof AdminDataShopeeIdRoute
  '/admin/data-shopee': typeof AdminDataShopeeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginLazyRoute
  '/register': typeof RegisterLazyRoute
  '/admin/brand': typeof AdminBrandRoute
  '/admin/hpp-produk': typeof AdminHppProdukRoute
  '/admin/data-shopee/$id': typeof AdminDataShopeeIdRoute
  '/admin/data-shopee/': typeof AdminDataShopeeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/register'
    | '/admin/brand'
    | '/admin/hpp-produk'
    | '/admin/data-shopee/$id'
    | '/admin/data-shopee/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/register'
    | '/admin/brand'
    | '/admin/hpp-produk'
    | '/admin/data-shopee/$id'
    | '/admin/data-shopee'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/register'
    | '/admin/brand'
    | '/admin/hpp-produk'
    | '/admin/data-shopee/$id'
    | '/admin/data-shopee/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  LoginLazyRoute: typeof LoginLazyRoute
  RegisterLazyRoute: typeof RegisterLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/hpp-produk': {
      id: '/admin/hpp-produk'
      path: '/hpp-produk'
      fullPath: '/admin/hpp-produk'
      preLoaderRoute: typeof AdminHppProdukRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/brand': {
      id: '/admin/brand'
      path: '/brand'
      fullPath: '/admin/brand'
      preLoaderRoute: typeof AdminBrandRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/data-shopee/': {
      id: '/admin/data-shopee/'
      path: '/data-shopee'
      fullPath: '/admin/data-shopee/'
      preLoaderRoute: typeof AdminDataShopeeIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/data-shopee/$id': {
      id: '/admin/data-shopee/$id'
      path: '/data-shopee/$id'
      fullPath: '/admin/data-shopee/$id'
      preLoaderRoute: typeof AdminDataShopeeIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminBrandRoute: typeof AdminBrandRoute
  AdminHppProdukRoute: typeof AdminHppProdukRoute
  AdminDataShopeeIdRoute: typeof AdminDataShopeeIdRoute
  AdminDataShopeeIndexRoute: typeof AdminDataShopeeIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminBrandRoute: AdminBrandRoute,
  AdminHppProdukRoute: AdminHppProdukRoute,
  AdminDataShopeeIdRoute: AdminDataShopeeIdRoute,
  AdminDataShopeeIndexRoute: AdminDataShopeeIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  LoginLazyRoute: LoginLazyRoute,
  RegisterLazyRoute: RegisterLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
